### ISSUE TITLE
German sources request

### ISSUE THREAD

**Issue by Nekuryo** [Rowdy-Avocado/Rowdycado-Extensions#1]
Some german sources would be greatly appreciated.

https://aniworld.to/
https://kinokiste.live/
https://filmpalast.sx/
https://s.to/

**Comment by RowdyRushya** [comment]
These are very good sources. I will work on it

**Comment by RowdyRushya** [comment]
@Nekuryo I will close this as we have added one source from the list. Create another request if you want to request more.
