### ISSUE TITLE
Manga dex lag problem 

### ISSUE THREAD

**Issue by Krishna-art-dev** [Rowdy-Avocado/Rowdycado-Extensions#10]
Manga dex able to read manga 
But it lags a lot 
Is there any way to fix it, if is please make it smooth

Thanks

**Comment by KillerDogeEmpire** [comment]
@Krishna-art-dev It's still a work in progress. I am sure that it will be improved in the future

**Comment by Krishna-art-dev** [comment]
> @Krishna-art-dev It's still a work in progress. I am sure that it will be improved in the future



> @Krishna-art-dev It's still a work in progress. I am sure that it will be improved in the future

I hope it will, I will close this issue now
