### ISSUE TITLE
mangadex bug

### ISSUE THREAD

**Issue by darkwaters-coder** [Rowdy-Avocado/Rowdycado-Extensions#11]
everytime i try to open an 'episode' my cloudstream crashes i don't why

**Comment by rushi-chavan** [comment]
Unable to replicate the issue. Please provide more details mentioned below.

Cloudstream version: 
Manga name:
Chapter no:

**Comment by darkwaters-coder** [comment]
am using the latest pre-release version 
any manga i tried to open chapter it crashes i don't know why

**Comment by rushi-chavan** [comment]
@darkwaters-coder there has been a major update in CS3 which made MangaDex work better. Please check again and close the issue if you no longer face the issue.
