### ISSUE TITLE
The Ultima settings has disappeared

### ISSUE THREAD

**Issue by mpaunovic** [Rowdy-Avocado/Rowdycado-Extensions#12]
No way to manage the Ultima settings anymore because the settings icon has disappeared. Can anyone else reproduce the issue?

**Comment by RowdyRushya** [comment]
Working fine for latest pre-release.

**Comment by mpaunovic** [comment]
> Working fine for latest pre-release.

Could you/somebody/anybody please try it on the stable release? Thank you!

**Comment by mpaunovic** [comment]
I just have updated Cloudstream to v4.4.0 and everything is working fine now. I'm closing this.

Thanks guys for all the hard work and keep it up!
