### ISSUE TITLE
Anitaku search shows duplicate

### ISSUE THREAD

**Issue by SittingDuck999** [Rowdy-Avocado/Rowdycado-Extensions#13]
Since Dub/Sub are merged, now when searching it shows 2 entries. Also it'd be cool if it'd syncing like Sora or Aniwave

**Comment by KillerDogeEmpire** [comment]
@SittingDuck999 it should have Anilist and Mal sync

**Comment by KillerDogeEmpire** [comment]
And I'm not sure the duplicate shows can be fixed. Sincerely on the site they are 2 different pages for sub and dub shows, so I don't think we could remove that. Also some shows can't merge the dub or sub, such as jujutsu kaisen.
