### ISSUE TITLE
cinezone "coming soon" again.

### ISSUE THREAD

**Issue by owengofficial** [Rowdy-Avocado/Rowdycado-Extensions#16]
![Screenshot_20240802-014645_CloudStream_Beta](https://github.com/user-attachments/assets/344d4cdc-1f53-49cd-9107-d1220b4ce10f)

need update key.
thanks.

**Comment by AvocadoWasSeized** [comment]
Keys updated

**Comment by Rayforest** [comment]
> Keys updated

Same 'coming soon' error again
