### ISSUE TITLE
Manga source request and question 

### ISSUE THREAD

**Issue by Krishna-art-dev** [Rowdy-Avocado/Rowdycado-Extensions#16]
If gonna add more manga sources then please consider adding comick and mangafire

Is there gonna be any way to download manga from cloudstream?

**Comment by rushi-chavan** [comment]
Downloading manga will be a very complex task as CS3 inbuilt download framework only supports video files. We need to build our own Download functionally and it is complex.

**Comment by Krishna-art-dev** [comment]
> Downloading manga will be a very complex task as CS3 inbuilt download framework only supports video files. We need to build our own Download functionally and it is complex.

Hmm the app developers doesn't wanna add manga support?

I should let this issue open till download support or you can just close it if download support is not planned

Thanks

**Comment by ABHIRAJ770** [comment]
Please add manga section pleeeaaaseeeee 🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏
