### ISSUE TITLE
Ultima

### ISSUE THREAD

**Issue by owencz1998** [Rowdy-Avocado/Rowdycado-Extensions#2]
Able to custom move where you want the home page to be organized as to your preference.

Also, on the TV UI using Ultima and using Sorastream, there's a limit on how many movies you can scroll through.

There's also a bug in the Ultima settings where scrolling through the providers there's no highlight, so it's hard to see what source I'm trying to select.

Many thanks to you all.

**Comment by rushi-chavan** [comment]
Hi, thanks for letting us know about bug in TV UI where you cannot see the selection and needs to be highlighed. We will work on it soon and fix it. 
Although, I just checked about your 2nd issue about Sorastream with limited content. As I can test it on my side, once you scroll all the way to the end in section on TV, it will take some time to load next set of posters. I know it is not smooth but it is working for me.

**Comment by owencz1998** [comment]
No worries mate I will check again might be my connection due to poor weather in the UK 😂but thanks for the awesome idea and hard work

**Comment by rushi-chavan** [comment]
- [x] Highlight while navigating through settings on TV https://github.com/Rowdy-Avocado/Rowdycado-Extensions/commit/363ca849c506e1a882d6d43c248624ead20aebf0
- [ ] Custom order for sections on home screen
- [ ] ~Limited titles while scrolling through sections~ (cannot be fixed right now)

**Comment by rushi-chavan** [comment]
closing the issue as all requests are completed!!!

**Comment by owencz1998** [comment]
Thanks so much @rushi-chavan 🙏

**Comment by owencz1998** [comment]
How does it work is number one would be top of the list mate
