### ISSUE TITLE
Site request

### ISSUE THREAD

**Issue by SaurabhKaperwan** [Rowdy-Avocado/Rowdycado-Extensions#21]
https://netfilm.app/
This website has multi audio feature.

**Comment by KillerDogeEmpire** [comment]
I'll look into it

**Comment by Krishna-art-dev** [comment]
> https://netfilm.app/ This website has multi audio feature.

From where do you find this awesome sites

**Comment by SaurabhKaperwan** [comment]
Someone requested this website in hexated repo

**Comment by Krishna-art-dev** [comment]
> Someone requested this website in hexated repo
Ooh
