### ISSUE TITLE
cinezone other source missing again.

### ISSUE THREAD

**Issue by owengofficial** [Rowdy-Avocado/Rowdycado-Extensions#25]
![349873671-fd2a195d-3bf2-4bf5-8a9e-712cec117018](https://github.com/user-attachments/assets/8b9bf340-baed-4fb0-9825-3d7d8eaaefa3)

should be 3 source there.

**Comment by lavara123** [comment]
@AvocadoWasSeized same problem https://github.com/Rowdy-Avocado/Rowdycado-Extensions/issues/16

**Comment by owengofficial** [comment]
![Screenshot_20240819-122921_Via](https://github.com/user-attachments/assets/c6a50156-6896-41cf-b7b9-5eb39762fcdc)

all movie&tv show are back now, but 2 server just missing, i check website cinezone they have 3 server its normal,.because im always using vidplay server to play movies/tvshow filemoon server its bad.

please fix server again.
thanks

**Comment by Th3-A6add0n** [comment]
> ![349873671-fd2a195d-3bf2-4bf5-8a9e-712cec117018](https://private-user-images.githubusercontent.com/90939972/358357365-8b9bf340-baed-4fb0-9825-3d7d8eaaefa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMzI5MTAsIm5iZiI6MTcyNDEzMjYxMCwicGF0aCI6Ii85MDkzOTk3Mi8zNTgzNTczNjUtOGI5YmYzNDAtYmFlZC00ZmIwLTk4MjUtM2Q3ZDhlYWFlZmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA1NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYzYyNzkwNjVmMDRhNDYxZWUwNmMxY2JmZmI2NjFhOGM3YWFhMWY3Y2FkMTNkMTIzZjM4MjEyZDdjYzRkMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8bJJ9-F_Ivhq6ZleHjqTjajrKEh6VmJMX7Z0Va1waTQ)
> 
> should be 3 source there.

In your case at least it's showing links, for me it's always "no links found", even when I'm able to access the website & watch on it.

**Comment by RowdyRushya** [comment]
solved
