### ISSUE TITLE
Ultima

### ISSUE THREAD

**Issue by SittingDuck999** [Rowdy-Avocado/Rowdycado-Extensions#3]
Hi, I hope you're doing great. 

First of all, you did a splendid work so thank you so much. 

Is it possible to add a startup homepage like a random show at the top akin to other extensions with potentially a search feature?

Also when you open CS to Ultima there's a splash screen that shows the none extension selected (only continue watching at the top) before it transitions to Ultima. 

Wishing you a blessed day.

**Comment by rushi-chavan** [comment]
- [ ] Random show banner at the top of home screen
- [ ] ~search feature~ (not useful as Ultima provides global content and similar global search already exists in the app)
- [ ] None extension selected before it transitions to Ultima (unable to replicate the issue and more clarification required)

**Comment by SittingDuck999** [comment]
So it shows this screen real quick then it disappear and it shows the full page (maybe force stop the app so it starts over and it may be visible). 

[Screenshot_20240228-092733_CloudStream Beta.jpg](https://github.com/Rowdy-Avocado/Rowdycado-Extensions/assets/148626924/46094483-e13f-4916-9f1f-f9ac2a84bd66)

**Comment by SittingDuck999** [comment]
Truly, the Ultimate extensions. Amazing work. 
If there's one last thing, since search doesn't work, is it possible to disable it so it doesn't show?

**Comment by rushi-chavan** [comment]
I forgot to disable it before push, lol 😂😂. I will close this and disable the search in next update or I might redirect it to global search.
