### ISSUE TITLE
Aniwave not working 

### ISSUE THREAD

**Issue by PresidentCTDragon** [Rowdy-Avocado/Rowdycado-Extensions#32]
Even after retry and changing the HTTPS over DNS, this error still occurs:
![Screenshot_20240822_123813](https://github.com/user-attachments/assets/598f8247-7833-4375-b6e8-ccb8a555414d)

**Comment by RowdyRushya** [comment]
This is Cloudflare issue which means that site owner has put some extra firewalls which is blocking CloudStream to access their content. We cannot do anything about this right now.
