### ISSUE TITLE
Ultima crashes when adding Hianime or Allwish(recent sub/dub) and reodering to top

### ISSUE THREAD

**Issue by SittingDuck999** [Rowdy-Avocado/Rowdycado-Extensions#36]
Also Hianime has no categories to choose from in Ultima

**Comment by RowdyRushya** [comment]
I tried to add few sections from both extensions in Ultima and it seems to be working fine on Ultima's Home Page.
Can you please try again and provide me step-by-step guide to generate this issue?
Also please provide what sections you selected from both extensions.

**Comment by SittingDuck999** [comment]
Resetting Ultima then clearing App cache fixed it.
