### ISSUE TITLE
Add Moviefiction website

### ISSUE THREAD

**Issue by SaurabhKaperwan** [Rowdy-Avocado/Rowdycado-Extensions#4]
https://moviefiction.com/

**Comment by Krishna-art-dev** [comment]
Hey can you able to tell me which source from Sora stream plays hindi movies and which hindi sources are not working now

**Comment by rushi-chavan** [comment]
> https://moviefiction.com/

I am not sure if this site requires VPN but I can see only 10-15 movies on this site. Not practical to implement this source.

> Hey can you able to tell me which source from Sora stream plays hindi movies and which hindi sources are not working now

This query is not related to 'Rowdycado Extensions' repo. Please ask this on relevant repo or you can also join CloudStream discord for general support.
