### ISSUE TITLE
[Ultima] MultiMovies (anime) No Links

### ISSUE THREAD

**Issue by DestroyerBDT** [Rowdy-Avocado/Rowdycado-Extensions#46]
Although MultiMovies as a extension has Anime, but when playing it through Ultima as a provider, it doesn't work

**Comment by phisher98** [comment]
Multimovies source is down as of now because of ddos

**Comment by DestroyerBDT** [comment]
> Multimovies source is down as of now because of ddos

This issue is of the time when MultiMovies was working and functional via Hindi Provider (_Now Phisher repo_)'s MultiMovies
