### ISSUE TITLE
Ultima extension not loading

### ISSUE THREAD

**Issue by ABrokenStar** [Rowdy-Avocado/Rowdycado-Extensions#5]
So i have selected 5 source extension for ultima. But many times 1 or 2 of them are down but others are working fine.. if any one source extension is down, ultima just throws the error to retry the connection and does not load the working extensions. 

Can you implement something that Ultima can skip those down sources and display only the working sources..

**Comment by rushi-chavan** [comment]
Hi, we have recently updated the Ultima to fix the issue you are facing https://github.com/Rowdy-Avocado/Rowdycado-Extensions/commit/c0cc1ea4953575e2bc55eaffe48292f70dfbcada
Please use the latest version of Ultima and let us know if you still face this issue with list of enabled sections and screenshots in next comment (you can close the issue if it is resolved).

**Comment by ABrokenStar** [comment]
Yeah. Working fine now.. this is THE best extension hands down. 
One issue is that, while scrolling on the rows, it repeats the title. I mean, it just shows about 10 titles repeatedly while scrolling left to right on rows.
