### ISSUE TITLE
HiAnime fails to load videos

### ISSUE THREAD

**Issue by sander1946** [Rowdy-Avocado/Rowdycado-Extensions#51]
Hello, i need help with HiAnime provider.
I have switched to HiAnime like a week ago, i really like how its implemented, but now i have the problem that its not able to find any links to play. This has been happening the last 2 days. There are no other providers that seem to have the features i want and be able to play anime. Idk if this is a problem kn HiAnime side (but there website works) or not, but i would like to know if this can be fixed. ![Screenshot_2024-12-10-21-57-41-45_a153ad7195ab131f51b38ebe0eab4033.jpg](https://github.com/user-attachments/assets/429d102b-80a1-4cd7-90fe-575ae6f19245)
![shared_text.txt](https://github.com/user-attachments/files/18085841/shared_text.txt)

**Comment by sander1946** [comment]
This is a version of the logcat that only has the no links found error

![shared_text.txt](https://github.com/user-attachments/files/18086069/shared_text.txt)

**Comment by Andro999b** [comment]
hianime uses megacloud/rabbitstream/vidstream to host videos. Recently, they updated their scrapping defense to use WASM compiled module, so no quick solution should be expected.

**Comment by sander1946** [comment]
HiAnime seems to work again!
