### ISSUE TITLE
Hianime been working for a while l,please update

### ISSUE THREAD

**Issue by jeyjai** [Rowdy-Avocado/Rowdycado-Extensions#59]
If you check hianime's extension in cloud stream from rowdy/avocados extension, it's working perfectly you get all the video mirrors and all the subtitles from all the animes I tested myself so maybe you can check his code from his guitar or maybe contact him in the log out apps discord which is the cloud stream discord and share some information

**Comment by AvocadoWasSeized** [comment]
this is the extension repo for rowdy avocado. I think this issue was meant for aniyomi extensions or something else.

**Comment by jeyjai** [comment]
> this is the extension repo for rowdy avocado. I think this issue was meant for aniyomi extensions or something else.

😅 Sorry, yes it was meant for the aniyomi.
