### ISSUE TITLE
Ultima Ultimate extension

### ISSUE THREAD

**Issue by M-BOUAB** [Rowdy-Avocado/Rowdycado-Extensions#6]
Ultima is my new favorite extension. Thank you RowdyRushya ♥️
I don't have any suggestions but just to keep it professional, if I had to make a suggestion, it would be to shorten the name of the posters rows titles by only showing the name of the row instead of also including the extension's name. Helps remove repetition as well.
Or make it optional in the Ultima extension settings if that's the better choice
Thanks again!

**Comment by rushi-chavan** [comment]
Thank you so much for your feedback on Ultima. I am really glad that you liked my work. ❤️
As you requsted, I have added the toggle to enable/disable extension name on home screen. I hope you like it and let us know if you have any more suggestions to further improve Ultima.
