### ISSUE TITLE
Anplay , animedekho and toonstream not working in Hindi providers 

### ISSUE THREAD

**Issue by 1llusionxD28** [Rowdy-Avocado/Rowdycado-Extensions#65]
Hi buddy , few days ago you told me about Hindi providers for anime but Anplay and animedekho were not working also toonstream stopped working yesterday... I request you humbly to fix them 
Thanks for your efforts

**Comment by phisher98** [comment]
@1llusionxD28 Wrong repo These Extensions are not here create issue here https://github.com/phisher98/HindiProviders

**Comment by 1llusionxD28** [comment]
Just submitted the report there sir
Thanks for your support

**Comment by 1llusionxD28** [comment]
Doing
