### ISSUE TITLE
Ultima Extension 

### ISSUE THREAD

**Issue by ABrokenStar** [Rowdy-Avocado/Rowdycado-Extensions#7]
When scrolling through a row, ultima keeps showing the same 10-12 titles repeatedly. It does not show (populate) complete row. As soon as we reach the end of a row and keep scrolling horizontally, the same titles visible on first screen keeps repeating.

Today on Superstream extension, or has completely stopped scrolling after one screen. I mean, you can't scroll horizontally after 15-16 titles..

**Comment by rushi-chavan** [comment]
I have tried these scenarios with multiple plugins but I am not getting repeated titles while scrolling on TV.
For Superstream (Hexated) as well I am able to scroll to right continously, although there is some delay when you reach at the last poster. But it will hardly take 2 sec to load next set of posters without repeating.

Please provide the screenshot or short video to show the problem you are facing.

**Comment by ABrokenStar** [comment]
https://github.com/Rowdy-Avocado/Rowdycado-Extensions/assets/161655511/2418483a-f319-45e0-9e0b-2dbfb683f14c

I'm attaching a short video. It's superstream plugin.. you can see that the same 5-6 posters get repeated again and again...

**Comment by phisher98** [comment]
@ABrokenStar Its a Extension Issue as It request for pages and its not a Ultima Extension issue its a Dev who created that Plugin for Movies is a issue contact them

**Comment by rushi-chavan** [comment]
Apparently, the Superstream from Hexated is very complexly developed which makes it difficult to incorporate with Ultima. Although, I will be looking into fixing this issue.

**Comment by ABrokenStar** [comment]
Thanx for the response. I hope you figure it out. Marking as closed for now.
