### ISSUE TITLE
Aniwave not working

### ISSUE THREAD

**Issue by Andro999b** [Rowdy-Avocado/Rowdycado-Extensions#7]
Videos not opens. Looks like they changed VRF algo or keys.

**Comment by AvocadoWasSeized** [comment]
@Andro999b it works for me, depending on if you are doing soft sub or sub/dub, vidplay doesn't work currently. if they removed the other sources temperarily then it will not work till they are re-added

**Comment by AvocadoWasSeized** [comment]
@Andro999b then I don't understand your issue. Aniwave is working dine for me and others. Try changing the server or using a vpn

**Comment by Andro999b** [comment]
Looks like problem related to my location or ISP. Clossing issue then.
