### ISSUE TITLE
Expanding Filipino Content Accessibility

### ISSUE THREAD

**Issue by noah010** [Rowdy-Avocado/Rowdycado-Extensions#72]
Dear Rowdy-Avocados Team,

I am writing to formally request the inclusion of https://moviesnipipay.me/ in the Rowdy-Avocado extension. 

Currently, there is a little to none extensions that offer a comprehensive selection of Filipino content. Having https://moviesnipipay.me/ would be a great step towards catering to a wider audience, particularly those seeking Filipino movies and shows. 

I believe this integration would be mutually beneficial for both Rowdy-Avocado and Filipino content enthusiasts. Thank you for considering my request.

Sincerely,

Noah

**Comment by rushi-chavan** [comment]
I am really impressed with your choice of words and I certainly guarantee you that I will be working on it.
> this integration would be mutually beneficial for both Rowdy-Avocado
Bruh I don't know what you are talking about. Where is the benefit for me in this?

**Comment by noah010** [comment]
> Bruh I don't know what you are talking about. Where is the benefit for me in this? 😆😂

I guess a spot in heaven...

although it is a pirated site. 🤣

**Comment by RowdyRushya** [comment]
I hope you like it. 🤗🤗 5302fc3ce10863de97edce0a7e56fddcffafbc4e
