### ISSUE TITLE
Add support for CinemaTV to CodeStream

### ISSUE THREAD

**Issue by Luna712** [Rowdy-Avocado/Rowdycado-Extensions#8]
CinemaTV is one that still works in SoraStream but doesn't in CodeStream

**Comment by AvocadoWasSeized** [comment]
hmmm, I'll look into it Luna. I think I f'd something up, as it should work

**Comment by AvocadoWasSeized** [comment]
hmmm nevermind, seems it was added

**Comment by Luna712** [comment]
@AvocadoWasSeized ah thanks could it be because it is commented out? https://github.com/Rowdy-Avocado/Rowdycado-Extensions/blob/e12edddb96b9c9d9e2ff4776329626c8bbba2a60/CodeStream/src/main/kotlin/com/KillerDogeEmpire/CodeStream.kt#L12

**Comment by Luna712** [comment]
nevermind that is just an import lol

**Comment by Luna712** [comment]
@AvocadoWasSeized Hmm it does work on CodeStream-Lite (as well as a few other sources) just not CodeStream
