### ISSUE TITLE
cinezone server is not complete as it should be.

### ISSUE THREAD

**Issue by owengofficial** [Rowdy-Avocado/Rowdycado-Extensions#9]
![Screenshot_20240718-160321_Via~01](https://github.com/user-attachments/assets/8c19c49a-b0ea-40a2-800f-784af1715b54)
![Screenshot_20240718-161204_CloudStream_Beta~01](https://github.com/user-attachments/assets/fd2a195d-3bf2-4bf5-8a9e-712cec117018)
On Cinezone website, all films/series have 3 servers, while for Cloudstream only 1 (Filemoon) 2 servers are missing. please check and please add the rest of the servers.

**Comment by AvocadoWasSeized** [comment]
@owengofficial it is known, a PR has been made in the app to fix it

**Comment by AvocadoWasSeized** [comment]
the servers will be back up once it is merged and fix, nothing else we can really do. I will now close this as it is being worked on and is pretty much done
