### ISSUE TITLE
Mangadex no link found error 

### ISSUE THREAD

**Issue by Krishna-art-dev** [Rowdy-Avocado/Rowdycado-Extensions#9]
I tried your manga dex it says no link found on any manga.
I will be a lot better for me if it get support of manga, then I will just gonna be using cloudstream and not other app like dantotsu

And I got to see that cs auto update progress function is not working, have to manually update everything in anilist simkl or any account 

Gonna make a issue for it in recloudstream but I just let you know that it is a problem

Thanks

**Comment by KillerDogeEmpire** [comment]
@Krishna-art-dev it works even if it says no links. Just keep trying. The reason it says no links found is cs3 is originally a streaming app. The extension from what I can tell, loads a menu after the no links found which shows the manga

**Comment by Krishna-art-dev** [comment]
@KillerDogeEmpire thanks bro it works after just some trying, thanks
